stages:
  - static-analysis
  - build
  - test
  - deploy

variables:
  DOCKER_COMPOSE_COMMAND: docker compose -f docker-compose.yml
  TAG: $CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG

build:
  stage: build
  tags:
    - project
  script:
    - $DOCKER_COMPOSE_COMMAND build
  artifacts:
    name: "build-artifacts"
    paths:
      - ./
    expire_in: 1 hour
    
static-analysis-service-1:
  stage: static-analysis
  tags:
    - project
  image:
    maven:3.9.9-eclipse-temurin-23
  script:
    - cd system-info-service-1-java
    - mvn checkstyle:checkstyle
    - mvn de.chkal.maven:gitlab-code-quality-plugin:generate
  artifacts:
    name: "static-analysis-results"
    reports:
      codequality:
        - system-info-service-1-java/target/gl-code-quality-report.json
    expire_in: 1 hour


static-analysis-state-service:
  stage: static-analysis
  tags:
    - project
  image:
    maven:3.9.9-eclipse-temurin-23
  script:
    - cd state-service
    - mvn checkstyle:checkstyle
    - mvn de.chkal.maven:gitlab-code-quality-plugin:generate
  artifacts:
    name: "static-analysis-results"
    reports:
      codequality:
        - state-service/target/gl-code-quality-report.json
    expire_in: 1 hour

static-analysis-dotnet:
  stage: static-analysis
  tags:
    - project
  image: 
    mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd system-info-service-2-dotnet/src/SystemInfoService2DotNet
    - dotnet tool restore
    - dotnet build
    - dotnet tool run roslynator analyze -o ./roslynator.xml --severity-level hidden || true
    - ls -la
    - dotnet tool run cq roslynator roslynator.xml gl-code-quality-report1.json %DIR
    - dotnet tool run cq sarif codeanalysis.sarif.json gl-code-quality-report2.json %DIR
    - dotnet tool run cq merge gl-code-quality-report.json gl-code-quality-report1.json  gl-code-quality-report2.json
  artifacts:
    paths:
      - system-info-service-2-dotnet/src/SystemInfoService2DotNet/roslynator.xml
      - system-info-service-2-dotnet/src/SystemInfoService2DotNet/gl-code-quality-report.json
    name: "static-analysis-results"
    reports:
      codequality: system-info-service-2-dotnet/src/SystemInfoService2DotNet/gl-code-quality-report.json
    expire_in: 1 hour

test_e2e:
  stage: test
  tags:
    - project
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip3 install -r tests/requirements.txt --break-system-packages
    - export TEST_ENV="true"
    - $DOCKER_COMPOSE_COMMAND up -d
    - sleep 20
    - export BASE_HOST="195.148.21.89"
  script:
    - pytest tests/e2e_tests.py
  after_script:
    - $DOCKER_COMPOSE_COMMAND down
  needs:
    - build

deploy:
  stage: deploy
  tags:
    - project
  script:
    - $DOCKER_COMPOSE_COMMAND up -d
  needs:
    - test_e2e