stages:
  - static-analysis
  - build
  - deploy

variables:
  DOCKER_COMPOSE_COMMAND: docker compose -f docker-compose.yml
  TAG: $CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG

build:
  stage: build
  tags:
    - project
  script:
    - $DOCKER_COMPOSE_COMMAND build
  artifacts:
    name: "build-artifacts"
    paths:
      - ./
    expire_in: 1 hour
    
static-analysis:
  stage: static-analysis
  tags:
    - project
  image:
    maven:3.9.9-eclipse-temurin-23
  script:
    - cd system-info-service-1-java
    - mvn checkstyle:checkstyle
    - mvn de.chkal.maven:gitlab-code-quality-plugin:generate
  artifacts:
    name: "static-analysis-results"
    reports:
      codequality:
        - system-info-service-1-java/target/gl-code-quality-report.json
    expire_in: 1 hour

deploy:
  stage: deploy
  tags:
    - project
  script:
    - $DOCKER_COMPOSE_COMMAND up -d
  needs:
    - build