services:
  service-1:
    build:
      context: ./system-info-service-1-java
    environment:
      - SERVICE_2_HOST=service-2:8080
    restart: on-failure
    networks:
      - exercise
    deploy:
      mode: replicated
      replicas: 3

  service-2:
    build:
      context: ./system-info-service-2-dotnet
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure
    networks:
      - exercise

  state-service:
    build:
      context: ./state-service
    environment:
      - NGINX_HOST=nginx:81
    restart: on-failure
    networks:
      - exercise

  nginx:
    build:
      context: ./nginx
    ports:
      - "8198:80"
      - "8197:81"
    networks:
      - exercise
    environment:
      - TEST_ENV=${TEST_ENV-false}
    depends_on:
      - service-1
      - service-2
    command: /bin/bash -c "envsubst '$${TEST_ENV}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

networks:
  exercise:
    driver: bridge

