name: laurovic-exercise

services:
  service-1:
    build:
      context: ./system-info-service-1-java
    environment:
      - SERVICE_2_HOST=service-2:8080
    restart: on-failure
    networks:
      - exercise
    deploy:
      mode: replicated
      replicas: 3

  service-2:
    build:
      context: ./system-info-service-2-dotnet
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure
    networks:
      - exercise

  nginx:
    build:
      context: ./nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - exercise
    depends_on:
      - service-1
      - service-2

networks:
  exercise:
    driver: bridge

