services:
  service-1:
    build:
      context: ./system-info-service-1-java
    image: laurovic-exercise1/system-info-service-1-java
    environment:
      - SERVICE_2_HOST=system-info-service-2-dotnet:8080
    restart: on-failure
    networks:
      - exercise
    deploy:
      mode: replicated
      replicas: 3

  service-2:
    build:
      context: ./system-info-service-2-dotnet
    image: laurovic-exercise1/system-info-service-2-dotnet
    container_name: system-info-service-2-dotnet
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure
    networks:
      - exercise

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - exercise
    depends_on:
      - service-1
      - service-2

networks:
  exercise:
    driver: bridge

