#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/SystemInfoService2DotNet/ && \
    dotnet build src/SystemInfoService2DotNet/ && \
    echo "Now, run the following to start the project: dotnet run -p src/SystemInfoService2DotNet/SystemInfoService2DotNet.csproj --launch-profile web"
