services:
  java-service:
    build:
      context: .
      target: java-service
    image: mms/java-service
    container_name: java-service
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - spring

networks:
  spring:
    driver: bridge

